#!/bin/bash

echo "Please enter your name:"

read -s USERNAME #takes input into username variable

echo "USERNAME entered username : $USERNAME"

echo "Please enter your password:"

reach -s PASSWORD
echo "Password entered: $PASSWORD"
